
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  // As operações de CLI (db push / migrate) usam a ligação directa (session
  // pooler, IPv4). O runtime usa DATABASE_URL (transaction pooler) do schema.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
